version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server-playground-api
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
